version: '3'

services:

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6380:6379'
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - '5433:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres' ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: app
    tty: true
    env_file:
      - .env
    volumes:
      - .:/code
      - static:/code/static
      - media:/code/media
    ports:
      - "8001:8000"
    depends_on:
      db:
        condition: service_healthy
    command: bash -c "python manage.py migrate && python manage.py create_users && python manage.py runserver 0.0.0.0:8000"

  celery:
    build: .
    container_name: celery
    restart: always
    tty: true
    env_file:
      - .env
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - app

  celery_beat:
    build: .
    container_name: celery_beat
    tty: true
    env_file:
      - .env
    command: celery -A config beat --loglevel=info
    depends_on:
      - redis
      - app


volumes:
  pg_data:
  static:
  media:


