# Generated by Django 4.2.6 on 2023-10-27 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50, verbose_name='место выполнения привычки')),
                ('time', models.TimeField(verbose_name='время выполнения привычки')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='приятная привычка')),
                ('periodicity', models.SmallIntegerField(default=1, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='награда')),
                ('estimated_time', models.SmallIntegerField(default=2, verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='публичная привычка')),
                ('connected_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
                'ordering': ('id',),
            },
        ),
    ]
