# Generated by Django 4.2.6 on 2023-10-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='last_reminder',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последнее напоминание'),
        ),
    ]
