# Generated by Django 4.2.6 on 2023-10-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0004_alter_habit_periodicity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habit',
            name='periodicity',
            field=models.SmallIntegerField(default=1, verbose_name='периодичность'),
        ),
    ]
